### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by botsbuzz** [raphabenoi/thesis#1]
Hi Raphael,

really interesting thesis and awesome project. Thank you for your effort on this!

I'm trying to start the project with no luck. 
`npm start`

got me the message
`[hurley] - Network configuration does not exist. Be sure to first create a new network with 'hurley new'`

Could you help me to solve the issue?

Many thanks,
Stefano

**Comment by raphabenoi** [comment]
Hi Stefano,

Thanks for your interest in it!

I’m travelling most of today and won’t be able to test it myself and give you direct feedback.
But looks to me like the problem lies with you not having a local blockchain running (what Hurley is there for). Maybe check out their documentation to make sure you have all the right prerequisites installed (correct node version etc).

If that doesn’t work, let me know and I’ll dig deeper into it.

Best,
Raphaël

On 5. Mar 2020, at 04:55, botsbuzz <notifications@github.com> wrote:

﻿

Hi Raphael,

really interesting thesis and awesome project. Thank you for your effort on this!

I'm trying to start the project with no luck.
npm start

got me the message
[hurley] - Network configuration does not exist. Be sure to first create a new network with 'hurley new'

Could you help me to solve the issue?

Many thanks,
Stefano

**Comment by botsbuzz** [comment]
Thank you for your kind reply Raphaël!

I solved the issue removing the folder 

`/Users/username/hyperledge`

But now I have another problem, I can't run tests. The command: 

`npm run test`

got me the following log:

`> hypenergy@0.1.0 test /Users/stefano/Downloads/thesis-master
> npm-run-all -s lerna:test


> hypenergy@0.1.0 lerna:test /Users/stefano/Downloads/thesis-master
> lerna exec npm run test

lerna notice cli v3.20.2
lerna info Executing command in 1 package: "npm run test"

> energymarket-cc@0.1.0 test /Users/stefano/Downloads/thesis-master/packages/energymarket-cc
> npm run build && mocha --inspect --debug=8888 -r ts-node/register tests/*.fabric.spec.ts --reporter spec


> energymarket-cc@0.1.0 build /Users/stefano/Downloads/thesis-master/packages/energymarket-cc
> npm run clean && tsc


> energymarket-cc@0.1.0 clean /Users/stefano/Downloads/thesis-master/packages/energymarket-cc
> rimraf dist client

Debugger listening on ws://127.0.0.1:8888/e7dfa121-6456-4913-b975-2be4f7e30cf8
For help see https://nodejs.org/en/docs/inspector


  CHAINCODE TEST SERIES
creating market instance 'MKT' as ORG 1 (LMO)
creating Public Grid: [object Object] 
    1) should create a LMO, public GRID, and a number of MarketParticipants
    2) should create an energy auction
    3) should place bids and ask from different participants
transaction returned with failure: {"name":"Error","status":500,"message":"Cannot read property 'readings' of undefined"}
transaction returned with failure: {"name":"Error","status":500,"message":"Cannot read property 'readings' of undefined"}
    4) should send a smart meter reading for AUC1 for each market participants
transaction returned with failure: {"name":"Error","status":500,"message":"[0] must be a `object` type, but the final value was: `null` (cast from the value `\"[\"`).\n If \"null\" is intended as an empty value be sure to mark the schema as `.nullable()`"}
Auction { _type: 'de.rli.hypenergy.auction' }
    5) should successfully escrow AUC1
    6) should successfully create an AUC2, place bids and asks, clear AUC2, and escrow AUC2
    7) should successfully create an AUC3, place bids and asks, clear AUC3, and escrow AUC3
    8) should successfully create an AUC4, place bids and asks, clear AUC4, and escrow AUC4
    9) should successfully create an AUC5, place bids and asks, clear AUC5, and escrow AUC5


  0 passing (2s)
  9 failing

  1) CHAINCODE TEST SERIES
       should create a LMO, public GRID, and a number of MarketParticipants:
     TypeError: Cannot read property '0' of undefined
      at /Users/stefano/Downloads/thesis-master/packages/energymarket-cc/tests/energymarket.fabric.spec.ts:143:144
      at <anonymous>

  2) CHAINCODE TEST SERIES
       should create an energy auction:
     AssertionError: expected undefined to deeply equal 'AUC1'
      at Object.<anonymous> (tests/energymarket.fabric.spec.ts:165:32)
      at step (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:139:27)
      at Object.next (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:120:57)
      at fulfilled (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:110:62)
      at <anonymous>

  3) CHAINCODE TEST SERIES
       should place bids and ask from different participants:
     Error: 
    CLIENT_RES_ERR
    There was a problem while invoking the chaincode
    Chaincode error, this is a wrapper around the responses

    Original stack:
    Error: transaction returned with failure: {"name":"Error","status":500,"message":"Bid sender and transaction sender do not match"}
    at self._endorserClient.processProposal (/Users/stefano/Downloads/thesis-master/node_modules/fabric-client/lib/Peer.js:140:36)
    at Object.onReceiveStatus (/Users/stefano/Downloads/thesis-master/node_modules/grpc/src/client_interceptors.js:1191:9)
    at InterceptingListener._callNext (/Users/stefano/Downloads/thesis-master/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/Users/stefano/Downloads/thesis-master/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/Users/stefano/Downloads/thesis-master/node_modules/grpc/src/client_interceptors.js:841:24)
    
      at ClientResponseError.BaseError [as constructor] (/Users/stefano/Downloads/thesis-master/node_modules/@worldsibu/convector-core-errors/src/base.error.ts:18:5)
      at new ClientResponseError (/Users/stefano/Downloads/thesis-master/node_modules/@worldsibu/convector-core-errors/src/client.errors.ts:16:5)
      at FabricControllerAdapter.<anonymous> (/Users/stefano/Downloads/thesis-master/node_modules/@worldsibu/convector-adapter-fabric/src/fabric.controller-adapter.ts:34:15)
      at step (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:139:27)
      at Object.throw (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:120:57)
      at rejected (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:111:69)
      at <anonymous>

  4) CHAINCODE TEST SERIES
       should send a smart meter reading for AUC1 for each market participants:
     TypeError: Cannot read property 'map' of undefined
      at /Users/stefano/Downloads/thesis-master/packages/energymarket-cc/tests/energymarket.fabric.spec.ts:284:152
      at <anonymous>

  5) CHAINCODE TEST SERIES
       should successfully escrow AUC1:
     TypeError: Cannot read property '0' of undefined
      at /Users/stefano/Downloads/thesis-master/packages/energymarket-cc/tests/energymarket.fabric.spec.ts:307:144
      at <anonymous>

  6) CHAINCODE TEST SERIES
       should successfully create an AUC2, place bids and asks, clear AUC2, and escrow AUC2:
     AssertionError: expected undefined to deeply equal 'AUC2'
      at /Users/stefano/Downloads/thesis-master/packages/energymarket-cc/tests/energymarket.fabric.spec.ts:358:34
      at step (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:139:27)
      at Object.next (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:120:57)
      at fulfilled (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:110:62)
      at <anonymous>

  7) CHAINCODE TEST SERIES
       should successfully create an AUC3, place bids and asks, clear AUC3, and escrow AUC3:
     AssertionError: expected undefined to deeply equal 'AUC3'
      at /Users/stefano/Downloads/thesis-master/packages/energymarket-cc/tests/energymarket.fabric.spec.ts:358:34
      at step (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:139:27)
      at Object.next (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:120:57)
      at fulfilled (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:110:62)
      at <anonymous>

  8) CHAINCODE TEST SERIES
       should successfully create an AUC4, place bids and asks, clear AUC4, and escrow AUC4:
     AssertionError: expected undefined to deeply equal 'AUC4'
      at /Users/stefano/Downloads/thesis-master/packages/energymarket-cc/tests/energymarket.fabric.spec.ts:358:34
      at step (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:139:27)
      at Object.next (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:120:57)
      at fulfilled (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:110:62)
      at <anonymous>

  9) CHAINCODE TEST SERIES
       should successfully create an AUC5, place bids and asks, clear AUC5, and escrow AUC5:
     AssertionError: expected undefined to deeply equal 'AUC5'
      at /Users/stefano/Downloads/thesis-master/packages/energymarket-cc/tests/energymarket.fabric.spec.ts:358:34
      at step (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:139:27)
      at Object.next (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:120:57)
      at fulfilled (/Users/stefano/Downloads/thesis-master/node_modules/tslib/tslib.js:110:62)
      at <anonymous>



npm ERR! code ELIFECYCLE
npm ERR! errno 9
npm ERR! energymarket-cc@0.1.0 test: `npm run build && mocha --inspect --debug=8888 -r ts-node/register tests/*.fabric.spec.ts --reporter spec`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the energymarket-cc@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stefano/.npm/_logs/2020-03-06T10_04_31_851Z-debug.log
lerna ERR! npm run test exited 9 in 'energymarket-cc'
lerna ERR! npm run test exited 9 in 'energymarket-cc'
npm ERR! code ELIFECYCLE
npm ERR! errno 9
npm ERR! hypenergy@0.1.0 lerna:test: `lerna exec npm run test`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the hypenergy@0.1.0 lerna:test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stefano/.npm/_logs/2020-03-06T10_04_31_908Z-debug.log
ERROR: "lerna:test" exited with 9.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hypenergy@0.1.0 test: `npm-run-all -s lerna:test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hypenergy@0.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stefano/.npm/_logs/2020-03-06T10_04_31_935Z-debug.log`

Any idea?

Best,
Stefano

**Comment by raphabenoi** [comment]
That doesn't look good haha!
I'll look into it this weekend

**Comment by botsbuzz** [comment]
Thank you Raphaël!

Any good news?

**Comment by raphabenoi** [comment]
Hi, 
Unfortunately no. 
On my machine, it has something to do with an update of MacOS. Some XCode problem. 
When you do `npm i` do you get any errors? Or everything is fine?

It is quite annoying because you have to use the right version of node etc. 
I'm currently very busy but have it on the radar. I will try solving my XCode problem and let you know what I found after that.

**Comment by botsbuzz** [comment]
Thank you so much for your help!

When I do `npm i` everything is fine. No errors.

**Comment by botsbuzz** [comment]
Hi Raphaël,

unfortunately I still haven't been able to solve the issue. 

I hope to do it with your help. 

In any case thank you very much.

**Comment by raphabenoi** [comment]
Hey,
What happens when you run:
`hurl invoke energymarket energymarket_createMarket "{\"id\":\"MKT\",\"auctionTime\":900000,\"gridBuyPrice\":25,\"gridSellPrice\":5}" -o org1 -u user1`
after `npm start`?

**Comment by botsbuzz** [comment]
Everything seems to be OK when I run:
`hurl invoke energymarket energymarket_createMarket "{\"id\":\"MKT\",\"auctionTime\":900000,\"gridBuyPrice\":25,\"gridSellPrice\":5}" -o org1 -u user1`

here the log:

> [hurley] - {"id":"MKT","auctionTime":900000,"gridBuyPrice":25,"gridSellPrice":5}
> [hurley] - Sending transaction as user1 in org org1...
> [hurley] - Transaction sent! VALID  SUCCESS 999b0b864b7457c9c6463e02745f17b2398f02c12edce2b3518a5bd0089d1c6b
> [hurley] - Result: {"type":"Buffer","data":[]}
> Cleaning up event hubs

No errors after `npm start` but I can't connect to the debugger at `http://localhost:8888`

**Comment by raphabenoi** [comment]
Well, this will not be comforting. But I can't manage to make that first transaction work! I don't know what happened. I read that the MacOS update brought some problems with it. But this is really annoying. 
Especially because it is really hard to debug.
I'll keep on investigating

**Comment by botsbuzz** [comment]
Hey Raphaël,

can you give me some suggestions on how to investigate to resolve the issue?

**Comment by sunshine366** [comment]
Dear Raphaël Haupt,

My research interests include energy blockchain and artificial intelligence. Recently, I found your codes of energy blockchain  and intended to understand them, which are very interesting.

However, according to the readme file within your project, I got an error
![error](https://user-images.githubusercontent.com/56723880/83968090-4f5c6600-a8f9-11ea-8ef7-c95477097f65.png)
（ `npm ERR! hypenergy@0.1.0 cc:package: `f() { npm run lerna:build; chaincode-manager --update --config ./$2.$1.config.json --output ./chaincode-$1 package; }; f "energymarket" "org1"`` ） while performing the second step (`npm start` ), which could not be solved. Thus, I would be very grateful if you could give me help . Thank you very much.

Best regards,
Gang
